source 'https://rubygems.org'

ruby '3.2.0'

gem 'rails', '~> 7.1.0'
gem 'pg'
gem 'puma'
gem 'rack-cors'
gem 'jbuilder'
gem 'bootsnap', require: false

group :development, :test do
  gem 'debug'
  gem 'rspec-rails'
end

group :development do
  gem 'web-console'
end