version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: portfolio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build: ./backend/django
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/portfolio
      - SECRET_KEY=your-secret-key
    volumes:
      - ./backend/django:/app

  laravel:
    build: ./backend/laravel
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=portfolio
      - DB_USERNAME=user
      - DB_PASSWORD=password
    volumes:
      - ./backend/laravel:/var/www/html

  rails:
    build: ./backend/rails
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/portfolio
      - RAILS_ENV=development
    volumes:
      - ./backend/rails:/app

volumes:
  postgres_data: